name: Pull Mirth Channels from Dev

on:
  schedule:
    - cron: "10/10 * * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - uses: actions/cache@v2
      id: cache-mirthsync
      with:
        path: mirthsync-2.1.1.tar.gz
        key: ${{ runner.os }}-mirthsync-2.1.1.tar.gz
        
    - name: Download mirthSync
      if: steps.cache-mirthsync.outputs.cache-hit != 'true'
      run: 
        curl -L -O https://github.com/SagaHealthcareIT/mirthsync/releases/download/2.1.1/mirthsync-2.1.1.tar.gz &&
        echo 'f06447d3de010a01c512a7a8bb60b8333ed9d2a29a12501e0aeaef1a3b81c66a  mirthsync-2.1.1.tar.gz' | sha256sum -c

    - name: Unpack mirthSync
      run:
        tar -xvzf mirthsync-2.1.1.tar.gz -C /opt &&
        ln -s /opt/mirthsync-2.1.1/bin/mirthsync.sh /usr/local/bin/mirthsync.sh
        
    - name: Check if secrets are set
      run: |
        if [ -z "$DEV_URL" ]; then echo "DEV_URL is missing"; else echo "DEV_URL is set"; fi
        if [ -z "$DEV_USER" ]; then echo "DEV_USER is missing"; else echo "DEV_USER is set"; fi
        if [ -z "$DEV_PASS" ]; then echo "DEV_PASS is missing"; else echo "DEV_PASS is set"; fi
      env:
        DEV_URL: ${{ secrets.DEV_URL }}
        DEV_USER: ${{ secrets.DEV_USER }}
        DEV_PASS: ${{ secrets.DEV_PASS }}
        
    - name: Test Connection with curl
      run: |
          echo "Attempting to connect to DEV_URL using curl..."
          curl -v $DEV_URL || echo "curl connection failed."
      env:
          DEV_URL: ${{ secrets.DEV_URL }}

    - name: Ping Server
      run: |
          # Extract hostname from DEV_URL (assuming DEV_URL includes a protocol)
          HOST=$(echo $DEV_URL | sed -E 's/https?:\/\/([^\/]+).*/\1/')
          echo "Pinging host: $HOST"
          ping -c 4 $HOST || echo "Ping failed. Host might be unreachable."
      env:
          DEV_URL: ${{ secrets.DEV_URL }}

        
    - name: mirthSync pull
      run: DEV_URL=${{ secrets.DEV_URL }} DEV_USER=${{ secrets.DEV_USER }} DEV_PASS=${{ secrets.DEV_PASS }} make pull-local

    # - name: Pull Channels from Mirth Dev Server
    #   run: |
    #     curl -X GET "http://<DEV_MIRTH_SERVER>:8443/api/channels" \
    #     -H "Authorization: Basic ${{ secrets.MIRTH_AUTH }}" \
    #     -o mirth_channels.json

    - name: Commit & Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add *
        git commit -m "Auto-pulled Mirth channels from Dev"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
